#!/bin/bash

echo "🔮 CODEX Crystal Archive - Available Services"
echo "=============================================="
echo ""
echo "✅ Python Web Interface (Basic):"
echo "   🌐 http://localhost:5001"
echo "   📝 Simple HTML interface with core functionality"
echo ""
echo "✅ Next.js React Website (Advanced):"
echo "   🌐 http://localhost:3001"
echo "   🎨 Modern UI with 3D crystal, animations, and interactive features"
echo ""
echo "🚀 Quick Access:"
echo "   - Basic Interface:  http://localhost:5001"
echo "   - Advanced Website: http://localhost:3001"
echo ""
echo "💡 The advanced website has:"
echo "   - 3D interactive crystal visualization"
echo "   - Smooth animations and transitions"
echo "   - Live demo with file upload"
echo "   - Modern responsive design"
echo "   - Particle background effects"
echo "   - Typewriter animations"
echo ""
